#!/usr/bin/env node

/**
 * Get Current OTP Script for Android App Testing
 * 
 * This script retrieves the OTP that was generated by your Android app,
 * solving the synchronization issue.
 */

const https = require('https');

async function getCurrentOtpFromApp(phoneNumber = '+94771234567') {
  return new Promise((resolve, reject) => {
    const options = {
      hostname: 'agrimarket-52z0pnlgu-kabilantharmaratnam-kpucas-projects.vercel.app',
      port: 443,
      path: `/api/auth/get-current-otp.js?phoneNumber=${encodeURIComponent(phoneNumber)}`,
      method: 'GET',
      headers: {
        'Content-Type': 'application/json'
      }
    };

    const req = https.request(options, (res) => {
      let responseData = '';
      res.on('data', (chunk) => { responseData += chunk; });
      res.on('end', () => {
        try {
          const response = JSON.parse(responseData);
          resolve({ statusCode: res.statusCode, data: response });
        } catch (error) {
          reject(error);
        }
      });
    });

    req.on('error', reject);
    req.end();
  });
}

async function main() {
  try {
    console.log('🔍 Getting OTP generated by your Android app...\n');
    
    const response = await getCurrentOtpFromApp();
    
    if (response.statusCode === 200 && response.data.success) {
      const data = response.data;
      console.log('✅ Found valid OTP from your app!');
      console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
      console.log('📱 Phone Number:', data.phoneNumber);
      console.log('🔑 OTP Code:', data.otp);
      console.log('⏰ Expires in:', data.minutesLeft, 'minutes');
      console.log('🕐 Generated at:', new Date(data.createdAt).toLocaleString());
      console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
      
      console.log('📋 Next Steps:');
      data.instructions.forEach((instruction, index) => {
        console.log(`${index + 1}. ${instruction}`);
      });
      
    } else if (response.statusCode === 404) {
      console.log('❌ No valid OTP found');
      console.log('💡 Solution:');
      console.log('1. Open your Android app');
      console.log('2. Enter phone number: +94771234567');
      console.log('3. Tap "Send OTP" button');
      console.log('4. Run this script again to get the OTP code');
      
    } else {
      console.log('❌ Error:', response.data.message);
    }
    
  } catch (error) {
    console.error('❌ Network Error:', error.message);
    console.log('\n💡 Troubleshooting:');
    console.log('1. Check your internet connection');
    console.log('2. Make sure the serverless backend is running');
    console.log('3. Try again in a few seconds');
  }
}

main();
