using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Text;
using System.Text.RegularExpressions;
using HtmlAgilityPack;

// Initialize QuestPDF
QuestPDF.Settings.License = LicenseType.Community;

// Configure global settings
QuestPDF.Settings.EnableCaching = true;

// Read the HTML file
string htmlContent = File.ReadAllText("message_10.html", Encoding.UTF8);

// Parse HTML and clean up the content
var htmlDoc = new HtmlDocument();
htmlDoc.LoadHtml(htmlContent);

// Extract and clean text content
var textContent = htmlDoc.DocumentNode.InnerText
    .Replace("\n", " ")
    .Replace("\r", " ")
    .Replace("\t", " ");

// Pre-process to remove IP address lines
textContent = Regex.Replace(textContent, @"IP Address:\s*\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}", "", RegexOptions.IgnoreCase);

// Enhanced cleanup patterns
var cleanupPatterns = new Dictionary<string, string>
{
    // Remove system messages
    {@"Generated by[^.]*\.", ""},
    {@"Contains data from[^.]*\.", ""},
    // Clean up message effects more efficiently while preserving emojis
    {@"Word effects\s*Word:\s*([^\n]*?)Animation effect:\s*([^\n]*?)Creation time:", "$1 $2"},
    // Remove duplicate spaces
    {@"\s+", " "}
};

foreach (var pattern in cleanupPatterns)
{
    textContent = Regex.Replace(textContent, pattern.Key, pattern.Value, RegexOptions.Multiline);
}

// Enhanced conversation pattern to capture more context
var conversationPattern = @"(Michael Icban|Aviegaille Icban)\s*(.*?)\s*((?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{1,2},\s+\d{4}\s+\d{1,2}:\d{2}(?::\d{2})?(?:am|pm))";
var matches = Regex.Matches(textContent, conversationPattern, RegexOptions.IgnoreCase);

// Enhanced conversation data structure with more context
var conversations = new List<(
    string Speaker, 
    string Message, 
    DateTime Timestamp, 
    bool IsReply, 
    string TimeOfDay,
    bool IsGap
)>();

string previousSpeaker = null;
DateTime? previousTimestamp = null;

foreach (Match match in matches)
{
    if (DateTime.TryParse(match.Groups[3].Value, out DateTime timestamp))
    {
        var message = match.Groups[2].Value.Trim();
        
        // Skip empty messages and IP address messages
        if (string.IsNullOrWhiteSpace(message) || message.Contains("IP Address:")) continue;

        // Determine time of day
        var timeOfDay = timestamp.Hour switch
        {
            >= 5 and < 12 => "Morning",
            >= 12 and < 17 => "Afternoon",
            >= 17 and < 22 => "Evening",
            _ => "Night"
        };

        // Determine if there's a significant gap
        bool isGap = previousTimestamp.HasValue && 
                    (timestamp - previousTimestamp.Value).TotalHours >= 12;

        var isReply = IsReplyMessage(previousSpeaker, match.Groups[1].Value, previousTimestamp, timestamp);

        conversations.Add((
            match.Groups[1].Value,
            message,
            timestamp,
            isReply,
            timeOfDay,
            isGap
        ));

        previousSpeaker = match.Groups[1].Value;
        previousTimestamp = timestamp;
    }
}

// Sort conversations by timestamp
conversations = conversations.OrderBy(c => c.Timestamp).ToList();

// Create enhanced structured content
var structuredContent = new StringBuilder();

// Add enhanced legend
structuredContent.AppendLine("=== CONVERSATION LEGEND ===");
structuredContent.AppendLine("MI: Michael Icban");
structuredContent.AppendLine("AI: Aviegaille Icban");
structuredContent.AppendLine("→ Indicates a reply within 5 minutes");
structuredContent.AppendLine("... Indicates a gap of 12+ hours");
structuredContent.AppendLine();

// Group by year and month with enhanced statistics
var currentYear = 0;
var currentMonth = 0;
var currentDay = 0;
var currentTimeOfDay = "";
var monthlyStats = new Dictionary<string, (int MessageCount, int RepliesCount)>();

foreach (var conv in conversations)
{
    if (conv.Timestamp.Year != currentYear)
    {
        if (currentYear != 0)
        {
            AddYearSummary(structuredContent, currentYear, monthlyStats);
            monthlyStats.Clear();
        }
        currentYear = conv.Timestamp.Year;
        structuredContent.AppendLine($"\n=== YEAR: {currentYear} ===");
    }
    
    var monthKey = conv.Timestamp.ToString("yyyy-MM");
    if (!monthlyStats.ContainsKey(monthKey))
    {
        monthlyStats[monthKey] = (0, 0);
    }
    monthlyStats[monthKey] = (
        monthlyStats[monthKey].MessageCount + 1,
        monthlyStats[monthKey].RepliesCount + (conv.IsReply ? 1 : 0)
    );

    if (conv.Timestamp.Month != currentMonth)
    {
        currentMonth = conv.Timestamp.Month;
        currentDay = 0; // Reset day when month changes
        structuredContent.AppendLine($"\n--- MONTH: {conv.Timestamp.ToString("MMMM")} ---");
    }

    if (conv.Timestamp.Day != currentDay)
    {
        currentDay = conv.Timestamp.Day;
        currentTimeOfDay = ""; // Reset time of day when day changes
        structuredContent.AppendLine($"\n{conv.Timestamp.ToString("dddd, MMMM dd")}");
    }

    if (conv.TimeOfDay != currentTimeOfDay)
    {
        currentTimeOfDay = conv.TimeOfDay;
        structuredContent.AppendLine($"[{currentTimeOfDay}]");
    }

    // Add gap indicator if needed
    if (conv.IsGap)
    {
        structuredContent.AppendLine("...");
    }

    // Enhanced message format
    var speakerInitial = conv.Speaker.StartsWith("Michael") ? "MI" : "AI";
    var replyIndicator = conv.IsReply ? "→ " : "";
    
    // Indent replies for better thread visualization
    var indentation = conv.IsReply ? "    " : "";
    structuredContent.AppendLine($"{indentation}[{conv.Timestamp.ToString("HH:mm")}] {replyIndicator}{speakerInitial}: {conv.Message.Trim()}");
}

// Add final year summary
AddYearSummary(structuredContent, currentYear, monthlyStats);

var organizedText = structuredContent.ToString();

// Calculate statistics
var charCount = organizedText.Length;
var wordCount = organizedText.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries).Length;
var lineCount = (organizedText.Length / 80) + 1;

Console.WriteLine("\nDocument Statistics (Enhanced Organization):");
Console.WriteLine($"Characters: {charCount:N0}");
Console.WriteLine($"Words: {wordCount:N0}");
Console.WriteLine($"Estimated Lines: {lineCount:N0}");
Console.WriteLine();

// Split into columns
var textLength = organizedText.Length;
var partLength = textLength / 4;
var parts = new string[4];

for (int i = 0; i < 4; i++)
{
    var startIndex = i * partLength;
    var length = (i == 3) ? textLength - startIndex : partLength;
    parts[i] = organizedText.Substring(startIndex, length);
}

// Create enhanced document
Document.Create(container =>
{
    container.Page(page =>
    {
        page.Size(PageSizes.A3.Landscape());
        page.Margin(0.5f, Unit.Centimetre);
        page.PageColor(Colors.White);
        
        page.Content().Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn();
            });

            for (int i = 0; i < 4; i++)
            {
                table.Cell().Padding(5).Column(column =>
                {
                    column.Item().Text(text =>
                    {
                        text.DefaultTextStyle(style => style
                            .FontSize(9)
                            .FontColor(Colors.Black)
                            .FontFamily("Courier New"));
                        text.Span(parts[i]);
                    });
                });
            }
        });

        page.Footer()
            .AlignCenter()
            .Text(x =>
            {
                x.DefaultTextStyle(style => style.FontSize(8).FontFamily("Courier New"));
                x.CurrentPageNumber();
            });
    });
})
.GeneratePdf("fb_conversation_simplified.pdf");

Console.WriteLine("Simplified conversation PDF has been generated successfully!");
Console.WriteLine("Check the 'fb_conversation_simplified.pdf' file in your project directory.");

// Helper methods
static bool IsReplyMessage(string previousSpeaker, string currentSpeaker, DateTime? previousTime, DateTime currentTime)
{
    if (previousSpeaker == null || previousTime == null)
        return false;
    
    return previousSpeaker != currentSpeaker && 
           (currentTime - previousTime)?.TotalMinutes < 5;
}

static void AddYearSummary(StringBuilder content, int year, Dictionary<string, (int MessageCount, int RepliesCount)> stats)
{
    if (!stats.Any())
    {
        content.AppendLine($"\n--- {year} Summary ---");
        content.AppendLine("No messages found in this year.");
        content.AppendLine();
        return;
    }

    var totalMessages = stats.Sum(x => x.Value.MessageCount);
    var totalReplies = stats.Sum(x => x.Value.RepliesCount);
    var mostActiveMonth = stats.OrderByDescending(x => x.Value.MessageCount).First();
    
    content.AppendLine($"\n--- {year} Summary ---");
    content.AppendLine($"Total Messages: {totalMessages}");
    content.AppendLine($"Total Replies: {totalReplies}");
    content.AppendLine($"Most Active Month: {DateTime.ParseExact(mostActiveMonth.Key, "yyyy-MM", null):MMMM} ({mostActiveMonth.Value.MessageCount} messages)");
    content.AppendLine();
}
