name: Repository Health Check

on:
  schedule:
    - cron: '0 12 * * 1'  # Weekly on Monday at noon
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check README exists
        run: |
          if [ ! -f README.md ]; then
            echo "❌ README.md missing"
            exit 1
          else
            echo "✅ README.md exists"
          fi
          
      - name: Validate links in README
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          
      - name: Check for security vulnerabilities
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
